# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:

print("Versión de NumPy:", np.__version__)
print("\nConfiguración de NumPy:")
np.show_config()

Versión de NumPy: 2.3.5

Configuración de NumPy:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.30
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-pref

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
a= np.random.rand(2, 3, 5)
print("\nFORMA 2 - random.rand() (valores entre 0 y 1):")
print("Array a2:")
print(a)




FORMA 2 - random.rand() (valores entre 0 y 1):
Array a2:
[[[0.62057641 0.19914027 0.1618891  0.27615853 0.57076295]
  [0.62917103 0.07881957 0.87086139 0.74441696 0.74513416]
  [0.83501916 0.3486067  0.99559865 0.67112573 0.90061146]]

 [[0.83574035 0.06479884 0.32013739 0.16788767 0.46045474]
  [0.4614399  0.45625228 0.12445832 0.06021066 0.95032716]
  [0.13456428 0.64938758 0.1174118  0.40205835 0.1183774 ]]]



### 4. Print a.


In [6]:
print(a)


[[[0.62057641 0.19914027 0.1618891  0.27615853 0.57076295]
  [0.62917103 0.07881957 0.87086139 0.74441696 0.74513416]
  [0.83501916 0.3486067  0.99559865 0.67112573 0.90061146]]

 [[0.83574035 0.06479884 0.32013739 0.16788767 0.46045474]
  [0.4614399  0.45625228 0.12445832 0.06021066 0.95032716]
  [0.13456428 0.64938758 0.1174118  0.40205835 0.1183774 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [14]:

b = np.ones((5, 2, 3))





### 6. Print b.


In [15]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [16]:
# a es 2x3x5 = 2 × 3 × 5 = 30 elementos
# b es 5x2x3 = 5 × 2 × 3 = 30 elementos


print(a.size) 
print(b.size) 
print(a.size == b.size) 

30
30
True



### 8. Are you able to add a and b? Why or why not?


In [19]:

try:
    resultado = a + b
    print("¡Sí se puede sumar!")
except ValueError as e:
    print(f"NO se puede sumar: {e}")
    print("Motivo: Las formas son diferentes - a es 2x3x5, b es 5x2x3")

NO se puede sumar: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
Motivo: Las formas son diferentes - a es 2x3x5, b es 5x2x3




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [23]:
# Transponer b para que tenga la misma estructura que a (2, 3, 5)
c = b.transpose(1, 2, 0)  # o también puedes usar: c = np.transpose(b, (1, 2, 0))

print(f"Forma original de b: {b.shape}")
# b es (5, 2, 3)
print(f"Forma de a (objetivo): {a.shape}")
# a es (2, 3, 5)

# Verificar resultado
print(f"\nForma de c después de transponer: {c.shape}")
print(f"¿c tiene forma (2, 3, 5)? {c.shape == (2, 3, 5)}")

# Mostrar algunos valores para verificar
print("\nPrimera matriz de b (antes de transponer):")
print(b[0, :, :])  # Primera matriz de b

print("\nPrimera matriz de c (después de transponer):")
print(c[0, :, :])  # Primera matriz de c

Forma original de b: (5, 2, 3)
Forma de a (objetivo): (2, 3, 5)

Forma de c después de transponer: (2, 3, 5)
¿c tiene forma (2, 3, 5)? True

Primera matriz de b (antes de transponer):
[[1. 1. 1.]
 [1. 1. 1.]]

Primera matriz de c (después de transponer):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [25]:
# Mostrar las formas actuales
print(f"Forma de a: {a.shape}")
print(f"Forma de c: {c.shape}")

# Sumar a y c
d = a + c

print(f"\n ¡SUMA EXITOSA!")
print(f"Forma de d (resultado): {d.shape}")
print(f"Tipo de datos de d: {d.dtype}")

# Mostrar algunos elementos para verificar
print("\nPrimeros elementos de a:")
print(a[0, 0, :5])  # Primera fila de a
print("\nPrimeros elementos de c:")
print(c[0, 0, :5])  # Primera fila de c
print("\nPrimeros elementos de d (a + c):")
print(d[0, 0, :5])  # Primera fila de la suma


print("Antes: a.shape = (2,3,5), b.shape = (5,2,3) → DIFERENTES")
print("Ahora: a.shape = (2,3,5), c.shape = (2,3,5) → IGUALES")
print("\n Para sumar arrays en NumPy, deben tener la MISMA FORMA")
print("   Después de transponer b → c, las dimensiones coinciden")

Forma de a: (2, 3, 5)
Forma de c: (2, 3, 5)

 ¡SUMA EXITOSA!
Forma de d (resultado): (2, 3, 5)
Tipo de datos de d: float64

Primeros elementos de a:
[0.62057641 0.19914027 0.1618891  0.27615853 0.57076295]

Primeros elementos de c:
[1. 1. 1. 1. 1.]

Primeros elementos de d (a + c):
[1.62057641 1.19914027 1.1618891  1.27615853 1.57076295]
Antes: a.shape = (2,3,5), b.shape = (5,2,3) → DIFERENTES
Ahora: a.shape = (2,3,5), c.shape = (2,3,5) → IGUALES

 Para sumar arrays en NumPy, deben tener la MISMA FORMA
   Después de transponer b → c, las dimensiones coinciden



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [26]:

# Mostrar array a
print("ARRAY a (valores originales):")
print(a)
print(f"Forma de a: {a.shape}")

# Mostrar array d (a + c)
print("\nARRAY d (a + c):")
print(d)
print(f"Forma de d: {d.shape}")


print("d = a + c")
print("Es decir, cada valor en d es la SUMA de:")
print("  - El valor en a en la misma posición")
print("  - El valor en c en la misma posición")


print("EJEMPLO (primera posición):")
print(f"a[0,0,0] = {a[0,0,0]:.4f}")
print(f"c[0,0,0] = {c[0,0,0]:.4f}")
print(f"d[0,0,0] = {d[0,0,0]:.4f}")
print(f"COMPROBACIÓN: {a[0,0,0]:.4f} + {c[0,0,0]:.4f} = {a[0,0,0] + c[0,0,0]:.4f}")
print(f"¿Coincide con d? {abs(d[0,0,0] - (a[0,0,0] + c[0,0,0])) < 0.0001}")


ARRAY a (valores originales):
[[[0.62057641 0.19914027 0.1618891  0.27615853 0.57076295]
  [0.62917103 0.07881957 0.87086139 0.74441696 0.74513416]
  [0.83501916 0.3486067  0.99559865 0.67112573 0.90061146]]

 [[0.83574035 0.06479884 0.32013739 0.16788767 0.46045474]
  [0.4614399  0.45625228 0.12445832 0.06021066 0.95032716]
  [0.13456428 0.64938758 0.1174118  0.40205835 0.1183774 ]]]
Forma de a: (2, 3, 5)

ARRAY d (a + c):
[[[1.62057641 1.19914027 1.1618891  1.27615853 1.57076295]
  [1.62917103 1.07881957 1.87086139 1.74441696 1.74513416]
  [1.83501916 1.3486067  1.99559865 1.67112573 1.90061146]]

 [[1.83574035 1.06479884 1.32013739 1.16788767 1.46045474]
  [1.4614399  1.45625228 1.12445832 1.06021066 1.95032716]
  [1.13456428 1.64938758 1.1174118  1.40205835 1.1183774 ]]]
Forma de d: (2, 3, 5)
d = a + c
Es decir, cada valor en d es la SUMA de:
  - El valor en a en la misma posición
  - El valor en c en la misma posición
EJEMPLO (primera posición):
a[0,0,0] = 0.6206
c[0,0,0] = 1.0000


### 12. Multiply a and c. Assign the result to e.


In [27]:
e = a * c

print("RESULTADO DE a * c (array e):")
print(e)
print(f"\nForma de e: {e.shape}")
print(f"Tipo de datos de e: {e.dtype}")


print("EJEMPLO DE MULTIPLICACIÓN:")
print(f"a[0,0,0] = {a[0,0,0]:.4f}")
print(f"c[0,0,0] = {c[0,0,0]:.4f}")
print(f"e[0,0,0] = {e[0,0,0]:.4f}")
print(f"COMPROBACIÓN: {a[0,0,0]:.4f} × {c[0,0,0]:.4f} = {a[0,0,0] * c[0,0,0]:.4f}")
print(f"¿Coincide con e? {abs(e[0,0,0] - (a[0,0,0] * c[0,0,0])) < 0.0001}")

RESULTADO DE a * c (array e):
[[[0.62057641 0.19914027 0.1618891  0.27615853 0.57076295]
  [0.62917103 0.07881957 0.87086139 0.74441696 0.74513416]
  [0.83501916 0.3486067  0.99559865 0.67112573 0.90061146]]

 [[0.83574035 0.06479884 0.32013739 0.16788767 0.46045474]
  [0.4614399  0.45625228 0.12445832 0.06021066 0.95032716]
  [0.13456428 0.64938758 0.1174118  0.40205835 0.1183774 ]]]

Forma de e: (2, 3, 5)
Tipo de datos de e: float64
EJEMPLO DE MULTIPLICACIÓN:
a[0,0,0] = 0.6206
c[0,0,0] = 1.0000
e[0,0,0] = 0.6206
COMPROBACIÓN: 0.6206 × 1.0000 = 0.6206
¿Coincide con e? True




### 13. Does e equal to a? Why or why not?


In [31]:
### [your code here]





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [32]:
### [your code here]




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [33]:
### [your code here]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [34]:
### [your code here]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [35]:
### [your code here]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]